import requests
from bs4 import BeautifulSoup
import re
import json
import time
from lxml.html import fromstring


movieYear = ['https://themoviesboss.cx/release/2022/',
 'https://themoviesboss.cx/release/2021/',
 'https://themoviesboss.cx/release/2020/',
 'https://themoviesboss.cx/release/2019/',
 'https://themoviesboss.cx/release/2018/',
 'https://themoviesboss.cx/release/2017/',
 'https://themoviesboss.cx/release/2016/',
 'https://themoviesboss.cx/release/2015/',
 'https://themoviesboss.cx/release/2014/',
 'https://themoviesboss.cx/release/2013/',
 'https://themoviesboss.cx/release/2012/',
 'https://themoviesboss.cx/release/2011/',
 'https://themoviesboss.cx/release/2010/',
 'https://themoviesboss.cx/release/2009/',
 'https://themoviesboss.cx/release/2008/',
 'https://themoviesboss.cx/release/2007/',
 'https://themoviesboss.cx/release/2006/',
 'https://themoviesboss.cx/release/2005/',
 'https://themoviesboss.cx/release/2004/',
 'https://themoviesboss.cx/release/2003/',
 'https://themoviesboss.cx/release/2002/',
 'https://themoviesboss.cx/release/2001/',
 'https://themoviesboss.cx/release/2000/',
 'https://themoviesboss.cx/release/1999/',
 'https://themoviesboss.cx/release/1998/',
 'https://themoviesboss.cx/release/1997/',
 'https://themoviesboss.cx/release/1996/',
 'https://themoviesboss.cx/release/1995/',
 'https://themoviesboss.cx/release/1994/',
 'https://themoviesboss.cx/release/1993/',
 'https://themoviesboss.cx/release/1992/',
 'https://themoviesboss.cx/release/1991/',
 'https://themoviesboss.cx/release/1990/',
 'https://themoviesboss.cx/release/1989/',
 'https://themoviesboss.cx/release/1988/',
 'https://themoviesboss.cx/release/1987/',
 'https://themoviesboss.cx/release/1986/',
 'https://themoviesboss.cx/release/1985/',
 'https://themoviesboss.cx/release/1984/',
 'https://themoviesboss.cx/release/1983/',
 'https://themoviesboss.cx/release/1982/',
 'https://themoviesboss.cx/release/1981/',
 'https://themoviesboss.cx/release/1980/',
 'https://themoviesboss.cx/release/1979/',
 'https://themoviesboss.cx/release/1978/',
 'https://themoviesboss.cx/release/1977/',
 'https://themoviesboss.cx/release/1976/',
 'https://themoviesboss.cx/release/1975/',
 'https://themoviesboss.cx/release/1974/',
 'https://themoviesboss.cx/release/1973/',
 'https://themoviesboss.cx/release/1972/',
 'https://themoviesboss.cx/release/1971/',
 'https://themoviesboss.cx/release/1970/',
 'https://themoviesboss.cx/release/1969/',
 'https://themoviesboss.cx/release/1968/',
 'https://themoviesboss.cx/release/1967/',
 'https://themoviesboss.cx/release/1966/',
 'https://themoviesboss.cx/release/1965/',
 'https://themoviesboss.cx/release/1964/',
 'https://themoviesboss.cx/release/1963/',
 'https://themoviesboss.cx/release/1962/',
 'https://themoviesboss.cx/release/1961/',
 'https://themoviesboss.cx/release/1960/']

movieUrls = ['https://themoviesboss.cx/release/2022/page/1/',
 'https://themoviesboss.cx/release/2022/page/2/',
 'https://themoviesboss.cx/release/2022/page/3/',
 'https://themoviesboss.cx/release/2022/page/4/',
 'https://themoviesboss.cx/release/2022/page/5/',
 'https://themoviesboss.cx/release/2022/page/6/',
 'https://themoviesboss.cx/release/2022/page/7/',
 'https://themoviesboss.cx/release/2022/page/8/',
 'https://themoviesboss.cx/release/2022/page/9/',
 'https://themoviesboss.cx/release/2022/page/10/',
 'https://themoviesboss.cx/release/2022/page/11/',
 'https://themoviesboss.cx/release/2022/page/12/',
 'https://themoviesboss.cx/release/2022/page/13/',
 'https://themoviesboss.cx/release/2022/page/14/',
 'https://themoviesboss.cx/release/2022/page/15/',
 'https://themoviesboss.cx/release/2022/page/16/',
 'https://themoviesboss.cx/release/2022/page/17/',
 'https://themoviesboss.cx/release/2022/page/18/',
 'https://themoviesboss.cx/release/2022/page/19/',
 'https://themoviesboss.cx/release/2022/page/20/',
 'https://themoviesboss.cx/release/2022/page/21/',
 'https://themoviesboss.cx/release/2022/page/22/',
 'https://themoviesboss.cx/release/2022/page/23/',
 'https://themoviesboss.cx/release/2022/page/24/',
 'https://themoviesboss.cx/release/2022/page/25/',
 'https://themoviesboss.cx/release/2022/page/26/',
 'https://themoviesboss.cx/release/2022/page/27/',
 'https://themoviesboss.cx/release/2022/page/28/',
 'https://themoviesboss.cx/release/2022/page/29/',
 'https://themoviesboss.cx/release/2022/page/30/',
 'https://themoviesboss.cx/release/2021/page/1/',
 'https://themoviesboss.cx/release/2021/page/2/',
 'https://themoviesboss.cx/release/2021/page/3/',
 'https://themoviesboss.cx/release/2021/page/4/',
 'https://themoviesboss.cx/release/2021/page/5/',
 'https://themoviesboss.cx/release/2021/page/6/',
 'https://themoviesboss.cx/release/2021/page/7/',
 'https://themoviesboss.cx/release/2021/page/8/',
 'https://themoviesboss.cx/release/2021/page/9/',
 'https://themoviesboss.cx/release/2021/page/10/',
 'https://themoviesboss.cx/release/2021/page/11/',
 'https://themoviesboss.cx/release/2021/page/12/',
 'https://themoviesboss.cx/release/2021/page/13/',
 'https://themoviesboss.cx/release/2021/page/14/',
 'https://themoviesboss.cx/release/2021/page/15/',
 'https://themoviesboss.cx/release/2021/page/16/',
 'https://themoviesboss.cx/release/2021/page/17/',
 'https://themoviesboss.cx/release/2021/page/18/',
 'https://themoviesboss.cx/release/2021/page/19/',
 'https://themoviesboss.cx/release/2021/page/20/',
 'https://themoviesboss.cx/release/2021/page/21/',
 'https://themoviesboss.cx/release/2021/page/22/',
 'https://themoviesboss.cx/release/2021/page/23/',
 'https://themoviesboss.cx/release/2021/page/24/',
 'https://themoviesboss.cx/release/2021/page/25/',
 'https://themoviesboss.cx/release/2021/page/26/',
 'https://themoviesboss.cx/release/2021/page/27/',
 'https://themoviesboss.cx/release/2021/page/28/',
 'https://themoviesboss.cx/release/2021/page/29/',
 'https://themoviesboss.cx/release/2020/page/1/',
 'https://themoviesboss.cx/release/2020/page/2/',
 'https://themoviesboss.cx/release/2020/page/3/',
 'https://themoviesboss.cx/release/2020/page/4/',
 'https://themoviesboss.cx/release/2020/page/5/',
 'https://themoviesboss.cx/release/2020/page/6/',
 'https://themoviesboss.cx/release/2020/page/7/',
 'https://themoviesboss.cx/release/2020/page/8/',
 'https://themoviesboss.cx/release/2020/page/9/',
 'https://themoviesboss.cx/release/2020/page/10/',
 'https://themoviesboss.cx/release/2019/page/1/',
 'https://themoviesboss.cx/release/2019/page/2/',
 'https://themoviesboss.cx/release/2019/page/3/',
 'https://themoviesboss.cx/release/2019/page/4/',
 'https://themoviesboss.cx/release/2019/page/5/',
 'https://themoviesboss.cx/release/2019/page/6/',
 'https://themoviesboss.cx/release/2019/page/7/',
 'https://themoviesboss.cx/release/2019/page/8/',
 'https://themoviesboss.cx/release/2019/page/9/',
 'https://themoviesboss.cx/release/2019/page/10/',
 'https://themoviesboss.cx/release/2018/page/1/',
 'https://themoviesboss.cx/release/2018/page/2/',
 'https://themoviesboss.cx/release/2018/page/3/',
 'https://themoviesboss.cx/release/2018/page/4/',
 'https://themoviesboss.cx/release/2018/page/5/',
 'https://themoviesboss.cx/release/2018/page/6/',
 'https://themoviesboss.cx/release/2018/page/7/',
 'https://themoviesboss.cx/release/2017/page/1/',
 'https://themoviesboss.cx/release/2017/page/2/',
 'https://themoviesboss.cx/release/2017/page/3/',
 'https://themoviesboss.cx/release/2017/page/4/',
 'https://themoviesboss.cx/release/2017/page/5/',
 'https://themoviesboss.cx/release/2016/page/1/',
 'https://themoviesboss.cx/release/2016/page/2/',
 'https://themoviesboss.cx/release/2016/page/3/',
 'https://themoviesboss.cx/release/2016/page/4/',
 'https://themoviesboss.cx/release/2016/page/5/',
 'https://themoviesboss.cx/release/2015/page/1/',
 'https://themoviesboss.cx/release/2015/page/2/',
 'https://themoviesboss.cx/release/2015/page/3/',
 'https://themoviesboss.cx/release/2015/page/4/',
 'https://themoviesboss.cx/release/2014/page/1/',
 'https://themoviesboss.cx/release/2014/page/2/',
 'https://themoviesboss.cx/release/2014/page/3/',
 'https://themoviesboss.cx/release/2013/page/1/',
 'https://themoviesboss.cx/release/2013/page/2/',
 'https://themoviesboss.cx/release/2013/page/3/',
 'https://themoviesboss.cx/release/2012/page/1/',
 'https://themoviesboss.cx/release/2012/page/2/',
 'https://themoviesboss.cx/release/2012/page/3/',
 'https://themoviesboss.cx/release/2011/page/1/',
 'https://themoviesboss.cx/release/2011/page/2/',
 'https://themoviesboss.cx/release/2010/page/1/',
 'https://themoviesboss.cx/release/2010/page/2/',
 'https://themoviesboss.cx/release/2009/page/1/',
 'https://themoviesboss.cx/release/2009/page/2/',
 'https://themoviesboss.cx/release/2008/page/1/',
 'https://themoviesboss.cx/release/2007/page/1/',
 'https://themoviesboss.cx/release/2007/page/2/',
 'https://themoviesboss.cx/release/2006/page/1/',
 'https://themoviesboss.cx/release/2006/page/2/',
 'https://themoviesboss.cx/release/2005/page/1/',
 'https://themoviesboss.cx/release/2004/page/1/',
 'https://themoviesboss.cx/release/2003/page/1/',
 'https://themoviesboss.cx/release/2002/page/1/',
 'https://themoviesboss.cx/release/2001/page/1/',
 'https://themoviesboss.cx/release/2000/page/1/',
 'https://themoviesboss.cx/release/1999/page/1/',
 'https://themoviesboss.cx/release/1998/page/1/',
 'https://themoviesboss.cx/release/1997/page/1/',
 'https://themoviesboss.cx/release/1996/page/1/',
 'https://themoviesboss.cx/release/1995/page/1/',
 'https://themoviesboss.cx/release/1994/page/1/',
 'https://themoviesboss.cx/release/1993/page/1/',
 'https://themoviesboss.cx/release/1992/page/1/',
 'https://themoviesboss.cx/release/1991/page/1/',
 'https://themoviesboss.cx/release/1990/page/1/',
 'https://themoviesboss.cx/release/1989/page/1/',
 'https://themoviesboss.cx/release/1988/page/1/',
 'https://themoviesboss.cx/release/1987/page/1/',
 'https://themoviesboss.cx/release/1986/page/1/',
 'https://themoviesboss.cx/release/1985/page/1/',
 'https://themoviesboss.cx/release/1984/page/1/',
 'https://themoviesboss.cx/release/1983/page/1/',
 'https://themoviesboss.cx/release/1982/page/1/',
 'https://themoviesboss.cx/release/1981/page/1/',
 'https://themoviesboss.cx/release/1980/page/1/',
 'https://themoviesboss.cx/release/1979/page/1/',
 'https://themoviesboss.cx/release/1978/page/1/',
 'https://themoviesboss.cx/release/1977/page/1/',
 'https://themoviesboss.cx/release/1976/page/1/',
 'https://themoviesboss.cx/release/1975/page/1/',
 'https://themoviesboss.cx/release/1974/page/1/',
 'https://themoviesboss.cx/release/1973/page/1/',
 'https://themoviesboss.cx/release/1972/page/1/',
 'https://themoviesboss.cx/release/1971/page/1/',
 'https://themoviesboss.cx/release/1970/page/1/',
 'https://themoviesboss.cx/release/1969/page/1/',
 'https://themoviesboss.cx/release/1968/page/1/',
 'https://themoviesboss.cx/release/1967/page/1/',
 'https://themoviesboss.cx/release/1966/page/1/',
 'https://themoviesboss.cx/release/1965/page/1/',
 'https://themoviesboss.cx/release/1964/page/1/',
 'https://themoviesboss.cx/release/1963/page/1/',
 'https://themoviesboss.cx/release/1962/page/1/',
 'https://themoviesboss.cx/release/1961/page/1/',
 'https://themoviesboss.cx/release/1960/page/1/']
movieLink = []

def pageGet():
    for i in range(len(movieUrls)):
        url = f"{movieUrls[i]}"
        response = requests.get(url)
        soup = BeautifulSoup(response.text,'lxml')
        link = soup.find_all('div',{'class':'poster'})
        j = str(link)
        f = re.findall(r'(https?://themoviesboss.cx/(movies|tvshows)/[^\s]+/)', j)
        for i in range(len(f)):
            print(f"{f[i][0]} - {f[i][1]}")
            movieLink.append(f[i][0])
        
pageGet()

with open(r'boss-links.txt', 'w') as fp:
    for link in movieLink:
        fp.write(f"{link}\n")
    print('Done')
